xianyi/OpenBLAS

- Makefile.system
- interface/gemv.c
- interface/ger.c
- kernel/x86_64/sgemv_t_4.c
ger and gemv call blas_memory_alloc/free which in their turn
call blas_lock. blas_lock create thread contention when matrices
are small and the number of thread is high enough. We avoid
call blas_memory_alloc by replacing it with stack allocation.
This can be enabled with:
make -DMAX_STACK_ALLOC=2048
The given size (in byte) must be high enough to avoid thread contention
and small enough to avoid stack overflow.
Fix #478
> Allow to do gemv and ger buffer allocation on the stack

- CONTRIBUTORS.md
- utest/common_utest.h
- utest/main.c
- utest/test_rotmg.c
Test requested in issue xianyi/OpenBLAS#484.
Run tests by applying the following change and then make:
diff --git a/Makefile.rule b/Makefile.rule
index bea1fe1..9852ff3 100644
--- a/Makefile.rule
+++ b/Makefile.rule
@@ -140,7 +140,7 @@ NO_AFFINITY = 1
-# UTEST_CHECK = 1
+UTEST_CHECK = 1
> Add test for drotmg bug fixed by 692b14c

- interface/gemv.c
- interface/ger.c
* stack_alloc_size is needed after the implementation call but it may be overwritten if it's optimized to a register, because some gemv implementation (ex: dgemv_n.S) do not restore all register (ex: r10).
* do the same in ger.c for the same reasons even if the bug has not been observed.
> Fix a segfault in gemv when MAX_STACK_ALLOC is set

- cblas.h
- cblas_noconst.h
- driver/others/Makefile
- driver/others/memory.c
- driver/others/openblas_get_num_procs.c
- driver/others/openblas_get_num_threads.c
- exports/gensymbol
Export the two routines `openblas_get_num_threads` and `openblas_get_num_procs` to obtain the number of threads that OpenBLAS uses and the number of processors that the hardware offers. These wrap existing routines.
This would be used in https://github.com/JuliaLang/julia/issues/10028.
> Introduce openblas_get_num_threads and openblas_get_num_procs

- cblas.h
- cblas_noconst.h
- common_c.h
- common_d.h
- common_interface.h
- common_level3.h
- common_macro.h
- common_param.h
- common_s.h
- common_z.h
- exports/gensymbol
- interface/Makefile
- interface/geadd.c
- interface/zgeadd.c
- kernel/Makefile.L3
- kernel/arm/geadd.c
- kernel/arm/zgeadd.c
In contrast to standard BLAS and LAPACK the ATLAS project includes a set of functions `ATL_?geadd` which realize the matrix-matrix addition `C := alpha * A + beta * C`  with the following Fortran signature:
ATL_?geadd(M, N, ALPHA, A, LDA, BETA, C, LDC) 
I implemented the one without further optimizations on top of `?axpby` for inside OpenBLAS. The calling sequence is 
?GEADD(M, N, ALPHA, A, LDA, BETA, C, LDC) 
in case of the Fortran interface. A cblas wrapper `cblas_?geadd` is supplied as well.
> Add ATLAS-style ?geadd function

- CONTRIBUTORS.md
- driver/others/memory.c
Possible fix for a race condition during shutdown causing a crash in `gotoblas_set_affinity()`. Please review.
> Fix issue #508

- kernel/x86_64/KERNEL.BULLDOZER
- kernel/x86_64/KERNEL.HASWELL
- kernel/x86_64/KERNEL.PILEDRIVER
- kernel/x86_64/KERNEL.SANDYBRIDGE
- kernel/x86_64/KERNEL.STEAMROLLER
- kernel/x86_64/cdot.c
- kernel/x86_64/cdot_microk_bulldozer-2.c
- kernel/x86_64/cdot_microk_haswell-2.c
- kernel/x86_64/cdot_microk_sandy-2.c
- kernel/x86_64/cdot_microk_steamroller-2.c
- kernel/x86_64/zdot.c
- kernel/x86_64/zdot_microk_bulldozer-2.c
- kernel/x86_64/zdot_microk_haswell-2.c
- kernel/x86_64/zdot_microk_sandy-2.c
- kernel/x86_64/zdot_microk_steamroller-2.c
The performance of cdot and zdot on newer platforms was very poor, compared to MKL and/or ACML.
OpenBLAS cdot- and zdot-kernels  on Haswell and Sandybridge are now always faster than MKL, The kernels for Bulldozer, Piledriver and Steamroller are now at least as fast than ACML.
Please see
https://sourceforge.net/p/slurm-roll/code/HEAD/tree/branches/benchmark/DOT/
for benchmark results.
> Added optimized cdot- and zdot-kernels

- kernel/x86_64/dgemv_t_4.c
Refs #478, #482, 9798481, fd9fd42
> Fix a buffer overflow with MAX_STACK_ALLOC size in dgemv_t

- interface/gemv.c
I tested this for several days and it run well so I think it can be merged. I wonder if it's correct (would need +7 instead of +3 ?) when using single precision but I was able to find a case where it's not.
Ref #478
> gemv: Ensure stack buffer is large enough to handle memory alignment

- c_check
This is necessary to avoid the false detection of a cross-compiling environment.
> Fix detection of ARM architectures in c_check.

- Makefile.system
- benchmark/Makefile
@wernsaar This one builds on my machine, but be aware of the ugly hard coding of the library path to libgfortran. I'm not a Makefile expert so I don't know a better way to fix this right now.
> Add vecLib benchmarks

- driver/others/memory.c
Refactor such that you can build with ALLOC_SHM=0. HughTLB
implicity depends on ALLOC_SHM=1. This patch allows
building for Android NDK r10d.
> Fix build with ALLOC_SHM=0 (Android NDK)

- Makefile.system
The standard way to disable OpenMP support is to set USE_OPENMP=0,
as indicated by other checks to see if USE_OPENMP equals 1. The
problem is obviously then that `ifdef USE_OPENMP` is very much not
what we want to test for. This causes tests to fail when no OpenMP
library is installed.
> Fix test execution when USE_OPENMP=0

- common.h
It seems that even with short-circuiting of the && operator, preprocessor fails when using __GLIBC_PREREQ(2, 17) if undefined.
This will happen when trying to compile for Android. Splitting the if condition in two parts solves it.
> Fixed error in common.h for Android compilation introduced by e12cf11

- cpuid_x86.c
- driver/others/dynamic.c
Ref #632 
This makes OpenBLAS compiles and also recognize my computer as Haswell instead of Prescott. I didn't find a complete list of CPUID's for skylake processors and only adding the model/family numbers for 6700K so there's almost certainly missing ones.
> Support Intel Skylake by Haswell kernels.

- lapack-netlib/lapacke/src/lapacke_clansy.c
- lapack-netlib/lapacke/src/lapacke_dlansy.c
- lapack-netlib/lapacke/src/lapacke_slansy.c
- lapack-netlib/lapacke/src/lapacke_zlansy.c
> Fix LAPACK_*lansy routines

- driver/others/blas_server.c
Add lacking headers declarations when compiling for Android ARM7.
Solves #673
> Add lacking headers declarations when compiling for Android ARM7. 

- c_check
This is necessary to avoid the false detection of a cross-compiling
environment.
> Fix detection of POWER architecture in c_check.

- openblas_config_template.h
Similar to #193, avoid using C99 `complex.h` when compiling C++ in Visual Studio (2013 or later).
> (Visual Studio) Don't use C99 complex numbers when building C++ code.

- exports/Makefile
use different names for `openblas*.renamed` between osx and other unices, fixes
```
Makefile:121: warning: overriding commands for target `../libopenblas64_p-r0.2.15.a.renamed'
Makefile:100: warning: ignoring old commands for target `../libopenblas64_p-r0.2.15.a.renamed'
```
also clean `*.renamed`
> fix makefile warning when renaming symbols

- benchmark/scripts/SCIPY/dsyrk.py
- benchmark/scripts/SCIPY/ssyrk.py
* Allocate a normal zeroed array instead of a random one.
* Write results into the array.
* Drop unneeded semicolons
* Use environment Python.
* Fix PEP8 issues.
* Use Fortran arrays.
> BENCH: Minor fixes in SciPy benchmarks

- Makefile
- Makefile.install
- Makefile.system
- driver/others/blas_server.c
- driver/others/memory.c
- exports/Makefile
- f_check
- getarch.c
Fixes #700 and a few other issues with the build on illumos (OmniOS to be exact).
> illumos fixes

- driver/others/memory.c
... not the number of allocated threads.
Close #760
> Let openblas_get_num_threads return the number of active threads

- Makefile.system
Define AWK as "nawk" for SunOS (actually Illumos) only - fixes #763
> Update Makefile.system to fix awk/nawk issue #763

- Makefile.system
partial revert of https://github.com/xianyi/OpenBLAS/commit/299cdcdc29999d591fcb300630d50b2986bfb6fc
from #696, was not explained why that was needed cc @wernsaar
> re enable Fortran optimization flag on windows

- Makefile.arm
- Makefile.system
- lapack-netlib/LAPACKE/include/lapacke_config.h
- lapack/lauu2/zlauu2_L.c
- lapack/lauu2/zlauu2_U.c
- lapack/potf2/zpotf2_L.c
- lapack/potf2/zpotf2_U.c
Hi,
Those are changes to allow building for ARMv7 on Android that I've always wanted to commit :
- First commit fixes the complex implementation of lapack lauu2 & potf2 #682.
- Second one is to solve linking errors (pthread is included in Android's bionic).
- Third restores a change @xianyi made (#682) but that was erased when updating LAPACKE.
> Fixes for Android build on ARMv7

- common_x86_64.h
Putting the procedure there is an MSVC-ism, where it is optional. GCC silently ignores and Clang errors, so it is best to remove this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/xianyi/openblas/801)
> Don't pass REALNAME to `.end`

- CONTRIBUTORS.md
- kernel/arm64/KERNEL.CORTEXA57
- kernel/arm64/cgemm_kernel_8x4.S
- kernel/arm64/ctrmm_kernel_8x4.S
- kernel/arm64/dgemm_kernel_4x4.S
- kernel/arm64/dgemm_kernel_4x8.S
- kernel/arm64/dgemm_kernel_8x4.S
- kernel/arm64/dtrmm_kernel_4x8.S
- kernel/arm64/dtrmm_kernel_8x4.S
- kernel/arm64/sgemm_kernel_16x4.S
- kernel/arm64/sgemm_kernel_8x8.S
- kernel/arm64/strmm_kernel_16x4.S
- kernel/arm64/strmm_kernel_8x8.S
Further optimizations to DGEMM for Cortex-A57
* Single core performance improved by ~10% 
Additional functional (non-optimized) GEMM assembly kernels for Cortex-A57
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/xianyi/openblas/802)
> DGEMM Optimizations for Cortex-A57

- common_x86.h
The first param of [_InterlockedExchange](https://msdn.microsoft.com/en-us/library/1s26w950.aspx) is **_long volatile *_**, however openblas uses **_BLASULONG *_** here, which leads to a compiler error under **VS2013** with CMake generated **Debug** settings.
This is a small fix. Similar type casting has already been present in common_x86_64.h but not here.
> Fix a minor compiler error in VisualStudio with CMake

- CONTRIBUTORS.md
- driver/others/memory.c
Tested to work with VS2013 and CMake. No need to call any initialization code now.
I used the 2nd solution posted [here](https://github.com/xianyi/OpenBLAS/issues/810#issuecomment-199701383). This technique has been used in Boost and Google Performance Tools. I adapted the code from Google Performance Tools for simplicity.
> Fix access violation on Windows while static linking in MSVC

- Makefile.rule
- getarch.c
> Allow to force to do not use -j as make argument

- c_check
A more robust approach, which can handle the special case when the path has dashes but the compiler name doesn't.
Also prevents CROSS_SUFFIX from being set while CROSS=0 just because a specific path is set for CC.
Fixes #605 and #857.
> Fixed cross-suffix detection for path that contains dashes

- driver/others/init.c
The change is for builds with NO_AFFINITY=1 commented.
In a NUMA system, if OPENBLAS_NUM_THREADS can be accommodated within the current node itself, then use only cores from this node.
Test results on a Haswell system with 2 NUMA nodes having 14 cores each (so total 28 cores).
OPENBLAS_NUM_THREADS was set to 14,
Performance before the change
$ OPENBLAS_NUM_THREADS=14 ./dgemm.goto 8192 8192
From : 8192  To : 8192 Step=1 : Trans=N
SIZE          Flops          Time
8192x8192 :   176706.49 MFlops   6.222248 sec
Performance after the change
$ OPENBLAS_NUM_THREADS=14 ./dgemm.goto 8192 8192
From : 8192  To : 8192 Step=1 : Trans=N
SIZE          Flops          Time
8192x8192 :   403372.82 MFlops   2.725795 sec
> Update NUMA CPU binding

- Makefile.install
- exports/Makefile
I was trying to compile and install OpenBLAS on OS X in a directory whose path contained a space. The compilation failed due to `CURDIR` in `export/Makefile`, and the installation due to `DESTDIR` in `Makefile.install`. This pull request wraps those two variables in quotation marks.
Regards,
Ivan
> Wrap CURDIR and DESTDIR in quotes

- interface/ztrmv.c
* Hopefully, because this was found by error and trial (dark magic)
* Ref #786
> Fix z/ctrmv stack allocation on AMD bulldozer and barcelona target

- common.h
In omp.h in Visual Studio, the definitions of omp_in_parallel and omp_get_num_procs are as follows:
```
_OMPIMP int _OMPAPI
omp_get_num_procs(
void
);
_OMPIMP int _OMPAPI
omp_in_parallel(
void
);
```
Where` _OMPIMP` is defined as` __declspec(dllimport)` and `_OMPAPI` is defined as `__cdecl`
MSVC treats the declaration of omp_in_parallel and omp_get_num_procs in common.h without the modifiers __declspec(dllimport) and __cdecl as a redefinition. The Visual Studio solution generated by CMake compiles successfully with this modification.
> Small change to allow compiling with USE_OPENMP on MSVC

- cpuid_x86.c
- driver/others/dynamic.c
- lapack-netlib/SRC/zgetrf2.f
1. Trivial typo correction (ZERBLA => XERBLA) to fix #910 (in line with lapack svn, bug and fix were apparently discussed in lapack "User Discussion" list as topic 4891 on Jan 24 but never under Bug reports)
2. Update dynamic.c and cpuid_x86.c for  Intel Braswell (ref #548)
> Update zgetrf2.f, cpuid_x86.c, dynamic.c

- Makefile.system
- c_check
- f_check
P6600/I6400 Build fix.. Reverted the changes which was done to support for MIPS n32 ABI
Signed-off-by: Shivraj Patil <shivraj.patil@imgtec.com>
> P6600/I6400 Build fix.

- common_arm.h
- common_mips.h
.func/.endfunc are gcc/gas-specific directives for generating stabs
debug information (and nothing more). This is near-useless now because
DWARF is commonly used, and moreover, this is not implemented in Clang.
Hence building OpenBLAS with Clang/ARM fails, and there is no sane way
to detect GCC vs. anything else using preprocessor.
Hence, just remove these directives.
> common_arm.h, common_mips.h: get rid of .func directives

- c_check
Fixes issues raised in #858 by @tkelman when CC contains arguments, i.e. `CC="x86_64-w64-mingw32-gcc -march=x86-64 -m64"`.
> Updated CROSS_SUFFIX regex to work with CC containing arguments

- utest/Makefile
Currently utest/Makefile is the only place that doesn't respect `LDFLAGS`. This causes when compiling with a compiler that is not in a standard location and runpath are specified through `LDFLAGS` for example. See https://trac.sagemath.org/ticket/21689 for such a case with `libgfortan`.
> make utest/Makefile respect LDFLAGS

- cpuid_x86.c
- driver/others/dynamic.c
- kernel/x86_64/dgemm_kernel_4x8_sandy.S
1. Fix #942 by using C++ style comments in the single affected file to work around hash character readahead bug in the builtin assembler of clang 3.9 
2. Add CPU model recognition for Intel "Pentium N3520" Bay Trail series Atom to close #983
> Change file comments to work around clang 3.9 assembler bug; add support for Bay Trail atom

- driver/others/init.c
- driver/others/memory.c
- getarch.c
to determine the number of CPU. In ARM platform,
online CPU will increasing when there is more workload.
while configure cpu is the max number of CPU.
> USE NPROCESSOR_CONF instaed of NPORCESSOR_ONLN

- CMakeLists.txt
Add CMAKE install target (copied from a patch provided by PrimarchOfTheSpaceWolves in #957)
> Add CMAKE install target

- CMakeLists.txt
- cpuid_x86.c
- driver/others/dynamic.c
Add cpu model detection for Intel 7xxx (Kaby Lake) and Xeon Phi x200 (Knights Landing) - both mapped to HASWELL - and for the latest crop of Intel "Apollo Lake" Atom cpus (NEHALEM)
> Add TARGETs for newer Intel CPUs - Kaby Lake, Knights Landing, Apollo Lake

- driver/others/blas_server.c
FreeBSD requires the same headers as Linux, NetBSD, Darwin, and Android in blas_server.c, but it was not included in the `#if`, thereby caused the build to fail on FreeBSD. This PR simply adds a check for FreeBSD along with the others.
> Include system headers for blas_server on FreeBSD

- c_check
- f_check
Fixes #920: building with the TDM-GCC flavor of mingw fails due to unrecognized argument
> Make c_check, f_check convert any --exclude-libs arguments to linker flags

- Makefile.system
This can cause strange messages when using a gcc compiled for a later version of OS X for example
```
gcc -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -m128bit-long-double -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=_ -DASMFNAME=__ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I.. -all_load -headerpad_max_install_names -install_name "/Users/fbissey/build/sage/local/var/tmp/sage/build/openblas-0.2.19/src/exports/../libopenblas_haswell-r0.2.19.dylib" -dynamiclib -o ../libopenblas_haswell-r0.2.19.dylib ../libopenblas_haswell-r0.2.19.a -Wl,-exported_symbols_list,osx.def  -L/Users/fbissey/build/sage/local/lib -L/Users/fbissey/build/sage/local/lib/gcc/x86_64-apple-darwin16.1.0/5.4.0 -L/Users/fbissey/build/sage/local/lib/gcc/x86_64-apple-darwin …
```
> Do not override MACOSX_DEPLOYMENT_TARGET if it is already defined.

- driver/others/xerbla.c
Fixes #1038, compiler warning generated when building with INTERFACE64=1
> Use appropriate int32/int64 format for error number in message string

- Makefile.system
Apply COMMON_OPT to the default FFLAGS as well to avoid building a non-optimized (and significantly slower than default netlib "Release" mode build) LAPACK by mistake, i.e. when FFLAGS is not provided via the environment at compile time. Fixes #843
> Apply COMMON_OPT to default FFLAGS

- lapack-netlib/LAPACKE/src/Makefile
Split obj list to allow building with mingw (argument list too long for the msys ar)
ref #1056 (previously seen as 325, 699)
> Split the obj list of LAPACKE 3.7.0

- cmake/lapack.cmake
- cmake/lapacke.cmake
... to get the cmake build working again. (More numerous 3.7.0 additions to follow)
> Update cmakefiles with changes from netlib 3.6.1

- cpuid_x86.c
- driver/others/dynamic.c
On my new computer, I found that OpenBLAS didn't recognize the CPU.  This was because it was getting an `exfamily` of 9, instead of the `8` that mapped to Kaby Lake in the existing OpenBLAS source.  This patch fixes that and adds in a few new CPUID mappings as best I could from the sandpile table.  Please verify that I interpreted the sandpile webpage correctly, there was some ambiguity with regards to huge pages and I just did my best to guess and choose the most reasonable choices.  With this patch, the tests all pass on my local machine.
> CPUID mappings for Core i5-7600K (Kaby Lake)

- driver/others/dynamic.c
Detect apollo lake like in cpuid_x86, otherwise it falls through to default ?prescott?
Also reading through there is dead break; remove that.
> Correct Apollo Lake CPUID identification in dynamic_arch builds

- lapack-netlib/LAPACKE/src/lapacke_cunmlq_work.c
- lapack-netlib/LAPACKE/src/lapacke_dormlq.c
- lapack-netlib/LAPACKE/src/lapacke_dormlq_work.c
- lapack-netlib/LAPACKE/src/lapacke_sormlq.c
- lapack-netlib/LAPACKE/src/lapacke_sormlq_work.c
- lapack-netlib/LAPACKE/src/lapacke_zunmlq_work.c
Copied from lapack https://github.com/Reference-LAPACK/lapack/pull/127  by vladimir-ch (with earlier changes from echeresh's  PR 115 "lapacke_*ormlq_work: move declarations under if" there as they touched some of the same files)
> LAPACKE: fix wrong number of columns in ?ormlq

- lapack-netlib/SRC/chbev_2stage.f
- lapack-netlib/SRC/dsbev_2stage.f
- lapack-netlib/SRC/ssbev_2stage.f
- lapack-netlib/SRC/zhbev_2stage.f
- lapack-netlib/SRC/ztrevc3.f
In a few files from netlib 3.7.0, an EXTERNAL declaration of subroutines missed a comma before the continuation line. This caused concatenated names to appear as unresolved external dependencies in the objects and library at least when compiled with ifort. Fixes #1069
> LAPACK: fix missing comma on continued lines

- lapack-netlib/TESTING/EIG/zchkhb2stg.f
- lapack-netlib/TESTING/EIG/zdrvst2stg.f
- lapack-netlib/TESTING/EIG/zerrst.f
From the epilog of #1069 - the Intel Fortran compiler treated these as unresolved external references
> TESTING/EIG: fix spurious EXTERNAL references to nonexistent functions

- kernel/x86_64/cscal_microk_bulldozer-2.c
- kernel/x86_64/cscal_microk_haswell-2.c
- kernel/x86_64/cscal_microk_steamroller-2.c
- kernel/x86_64/dscal.c
- kernel/x86_64/zscal_microk_bulldozer-2.c
- kernel/x86_64/zscal_microk_haswell-2.c
- kernel/x86_64/zscal_microk_steamroller-2.c
Hi,
My ASM is bit rusty, please let me know if i am wrong. ^_^ 
Code below would not work for ICC, it would work for GCC or PGI. I assume both compiler do not do much of checking on ASM code.
```
__asm__ __volatile__
(  mov
:
: "r" (XXX), ....
: "cc", "%0", "%1", "%2",
```
In GCC manual, I see following explanation:
> You may not write a clobber description in a way that overlaps with an input or output operand. For example, you may not have an operand describing a register class with one member if you mention that register in the clobber list. Variables declared to live in specific registers (see Explicit Reg Vars), and used as asm input or output operands must have no part mentioned in the clobber description. There is no way for you to specify that an input operand is modified without …
> remove input from clobbered list

- cpuid_x86.c
> Fix core detection for Kaby Lake without AVX (G4560)

- interface/zimatcopy.c
Temp buffer is leaked in (unlikely) fall-through path, now no more.
> Address unlikely memleak in zimatcopy interface

- lapack-netlib/SRC/dbdsqr.f
- lapack-netlib/SRC/sbdsqr.f
This is/was https://github.com/Reference-LAPACK/lapack/issues/135: Unless compiled with -fdefault-integer-8, sufficiently large matrices (N>18918) would trigger an integer overflow in the calculation of the iteration limit. This would lead to an immediate error return without any iterations having been performed.
> Fix integer overflow in LAPACK DBDSQR, SBDSQR

- kernel/power/casum_microk_power8.c
- kernel/power/dgemv_n_microk_power8.c
- kernel/power/sasum_microk_power8.c
Further fixes on top of 9e2f316ed.  Writing some doco for gcc on
inline assembly woke me up to some more errors.
- dgemv_kernel_4x4 asm did not mention *ap as a memory input, and
*y is both read and write.
- sasum_kernel_32 and casum_kernel_16 did not use %x for a vsx insn
operand, a problem if the "=f" sum output was ever allocated a vsx
reg in the altivec set.  This might be possible with inlining and
future gcc optimisation.
> Power8 inline assembly tweaks

- driver/others/dynamic.c
> Fix dynamic detection for ZEN CPUs.

- CMakeLists.txt
- cmake/openblas.pc.in
* Multi-lib distributions need to change the libdir
which is only portably possible with `GNUInstallDirs`.
* Multi-arch distributions such as Debian and Exherbo
need to be able to change the bindir.
> Use GNUInstallDirs to allow changing target directories

- cpuid_zarch.c
Really detect CPU (or rather system) type on z Systems (zArch) machines. Successfully tested on zEC12 and z13.
> detect CPU on zArch

- driver/others/memory.c
This PR fixes some issues I noticed in `driver/others/memory.c` while debugging the MIPS threading issues. Both appear to have been programming mistakes.
The first commit moves the `position < NUM_BUFFERS` condition to the front of the `&&` so it actually has an effect (it was being optimized away before).
The second commit ensures the case where `position == NUM_BUFFERS` is handled correctly in `blas_memory_alloc`. Having said that, this situation is pretty unlikely since `NUM_BUFFERS` is supposed to be greater than the number of CPUs (according to its definition in `common.h` anyway).
> Fixes to driver/others/memory.c

- common_mips.h
- common_mips64.h
https://bugs.debian.org/861486
This PR fixes some threading issues on MIPS found while trying to build Julia in Debian.
The first commit implements `MB` and `WMB` on MIPS (using GCC builtins, but hopefully that's fine). The second commit removes the broken `blas_lock` implementations so the code falls back to using GCC builtins which do work correctly on MIPS.
> MIPS threading fixes

- exports/Makefile
Android does not support versioned SONAME entries, ref. #1173
> Build shared library on Android without SONAME versioning

- Makefile.power
- README.md
IBM MASS library is upgraded to 8.1.5 and 8.1.3 is not available.
Update README.md and Makefile.power to use version 8.1.5 of libxlmass.
> build: fix libxlmass errors building on Power CPU

- CMakeLists.txt
- cmake/prebuild.cmake
- cmake/system.cmake
- driver/others/memory.c
- gen_config_h.c
- utest/CMakeLists.txt
This change adds 64 bit build support for Microsoft Visual Studio. 
Debug and Retail builds are built in separate directories for MSVC.
PDB symbols are generated for both Debug and Retail.
Added dependencies so that building ALL_BUILD in MSVC builds everything in the right order and only needs to be done once.
Fixed an issue with gen_config_h where the Microsoft scanf returns a different value than gnu scanf when hitting the EOL marker.
gen_config_h.exe is built during cmake like getarch.exe and getarch_2nd.exe.  I'm doing this to enable Windows UWP build support later.
> Add 64bit support for Microsoft Visual Studio

- driver/level3/syrk_thread.c
Stride calculation fix copied from https://github.com/wernsaar/OpenBLAS/commit/88900e1
This is known to fix #1117
> fixed syrk_thread.c taken from wernsaar

- driver/others/init.c
Fixes #1210, compilation on RHEL5 with affinity enabled
> Add sched_getcpu implementation for pre-2.6 glibc

- kernel/arm/axpy_vfp.S
- kernel/arm/cgemm_kernel_2x2_vfp.S
- kernel/arm/cgemm_kernel_2x2_vfpv3.S
- kernel/arm/cgemv_n_vfp.S
- kernel/arm/cgemv_t_vfp.S
- kernel/arm/ctrmm_kernel_2x2_vfp.S
- kernel/arm/ctrmm_kernel_2x2_vfpv3.S
- kernel/arm/rot_vfp.S
- kernel/arm/scal_vfp.S
- kernel/arm/zgemm_kernel_2x2_vfp.S
- kernel/arm/zgemm_kernel_2x2_vfpv3.S
- kernel/arm/zgemv_n_vfp.S
- kernel/arm/zgemv_t_vfp.S
- kernel/arm/ztrmm_kernel_2x2_vfp.S
- kernel/arm/ztrmm_kernel_2x2_vfpv3.S
clang is not recognizing some pre-UAL VFP mnemonics like fnmacs, fnmacd,
fnmuls and fnmuld. Replaced them with equivalent UAL mnemonics which are
vmls.f32, vmls.f64, vnmul.f32 and vnmul.f64 respectively.
> arm: Fix clang compilation for ARMv7

- cpuid_x86.c
These appear to be unintended side effects of PR #1091, probably causing #1232
> Fix unintentional fall-through cases in get_cacheinfo

- driver/level2/gbmv_thread.c
- driver/level2/sbmv_thread.c
- driver/level2/spmv_thread.c
- driver/level2/tbmv_thread.c
- driver/level2/tpmv_thread.c
- driver/level2/trmv_thread.c
Fix #660 #1089 
Maybe change weights in 01a119abfcdecbb640c5bfcb52a1771253b14513 5155e3f5090aa313ce342f4bc0880db63208c5a5
Essentially buffer[size] is accessed at buffer[size+1] in last loop. It is visible when build machine  is same as run machine, distribution packages build with lots of spare thread slots and unlikely are affected.
It is not a fix, just it adds blank where otherwise nearby structure is corrupted to no gdb-recognition.
Probably there are others, I just scanned nearby lines with [x] and [y+1] and looked at [x]
> Fix write past fixed size buffer

- cpuid_x86.c
Needs testing as the implementation of cpuid_count  may break some systems. Not sure if there is an easier solution to the problem of passing subleaf values to cpuid page 4. (This is intended to fix #1232 at some point)
> Use cpuid 4 with subleafs to query L1 cache size on Intel processors

- driver/others/init.c
- driver/others/memory.c
Reverting my cgroups PR 1239 due to unsafe use of __GLIBC_PREREQ that breaks non-glibc builds
> Revert "Honor cgroup/cpuset limits when enumerating cpus"

- driver/others/init.c
- driver/others/memory.c
Unsafe usage of the __GLIBC_PREREQ macro lead to build breakage on non-glibc systems
> Revert #1246, "honor cgroup/cpuset limits" for now
