lapack-netlib/lapacke/include/lapacke_config.h
=> Move #include statements outside extern "C" blocks

kernel/x86_64/KERNEL.BULLDOZER, kernel/x86_64/KERNEL.HASWELL, kernel/x86_64/KERNEL.SANDYBRIDGE, kernel/x86_64/ddot.c, kernel/x86_64/ddot_microk_haswell-2.c, kernel/x86_64/ddot_microk_sandy-2.c, kernel/x86_64/sdot.c, kernel/x86_64/sdot_microk_haswell-2.c, kernel/x86_64/sdot_microk_sandy-2.c, lapack-netlib/TESTING/sep.in
added optimized sdot- and ddot-kernels for Haswell and Sandybridge
=> added optimized sdot- and ddot-kernels for Haswell and Sandybridge

benchmark/Makefile, benchmark/zdot-intel.c, benchmark/zdot.c, kernel/x86_64/KERNEL.HASWELL, kernel/x86_64/KERNEL.PILEDRIVER, kernel/x86_64/KERNEL.SANDYBRIDGE, kernel/x86_64/daxpy.c, kernel/x86_64/daxpy_microk_haswell-2.c, kernel/x86_64/daxpy_microk_sandy-2.c, kernel/x86_64/saxpy.c, kernel/x86_64/saxpy_microk_haswell-2.c, kernel/x86_64/saxpy_microk_sandy-2.c
added optimized saxpy- and daxpy-kernel for haswell and sandybridge.
For Ivybridge, I can't help, because I don't have access to such a machine
=> added optimized saxpy- and daxpy-kernel for haswell and sandybridge

kernel/x86_64/KERNEL.HASWELL, kernel/x86_64/KERNEL.SANDYBRIDGE, kernel/x86_64/caxpy.c, kernel/x86_64/caxpy_microk_bulldozer-2.c, kernel/x86_64/caxpy_microk_haswell-2.c, kernel/x86_64/caxpy_microk_sandy-2.c, kernel/x86_64/caxpy_microk_steamroller-2.c
=> Optimized  caxpy-kernels

kernel/x86_64/KERNEL.HASWELL, kernel/x86_64/KERNEL.SANDYBRIDGE, kernel/x86_64/zaxpy.c, kernel/x86_64/zaxpy_microk_haswell-2.c, kernel/x86_64/zaxpy_microk_sandy-2.c, kernel/x86_64/zaxpy_microk_steamroller-2.c, lapack-netlib/TESTING/sep.in, lapack-netlib/TESTING/zctest.in
=> added optimized zaxpy-kernels

Makefile, benchmark/Makefile, benchmark/asum.c, benchmark/scal.c, common_arm.h, kernel/x86_64/KERNEL.HASWELL, kernel/x86_64/KERNEL.SANDYBRIDGE, kernel/x86_64/dsymv_L.c, kernel/x86_64/dsymv_L_microk_haswell-2.c, kernel/x86_64/dsymv_L_microk_sandy-2.c, kernel/x86_64/dsymv_U.c, kernel/x86_64/dsymv_U_microk_haswell-2.c, kernel/x86_64/dsymv_U_microk_sandy-2.c, lapack-netlib/TESTING/EIG/Makefile, lapack-netlib/TESTING/LIN/Makefile, make.inc
added optimized dsymv kernels for haswell and sandybridge. Dsymv is heavily used by ELK.
=> added optimized dsymv kernels for haswell and sandybridge

kernel/x86_64/KERNEL.HASWELL, kernel/x86_64/KERNEL.SANDYBRIDGE, kernel/x86_64/ssymv_L.c, kernel/x86_64/ssymv_L_microk_haswell-2.c, kernel/x86_64/ssymv_L_microk_sandy-2.c, kernel/x86_64/ssymv_U.c, kernel/x86_64/ssymv_U_microk_haswell-2.c, kernel/x86_64/ssymv_U_microk_sandy-2.c
added optimized ssymv kernels for haswell and sandybridge
=> added optimized ssymv kernels for haswell and sandybridge

kernel/x86_64/daxpy.c, kernel/x86_64/ddot.c, kernel/x86_64/saxpy.c, kernel/x86_64/sdot.c
optimized some blas level1 kernels for increments != 1
=> optimized some blas level1 kernels for increments != 1

benchmark/Makefile, benchmark/ger.c, kernel/x86_64/caxpy.c, kernel/x86_64/cdot.c, kernel/x86_64/daxpy.c, kernel/x86_64/ddot.c, kernel/x86_64/zaxpy.c, kernel/x86_64/zdot.c
added benchmarks for zgeru and cgeru
=> added benchmarks for zgeru and cgeru

kernel/x86_64/dgemv_n_4.c, kernel/x86_64/dgemv_n_microk_haswell-4.c, kernel/x86_64/dgemv_n_microk_nehalem-4.c, kernel/x86_64/sgemv_n_4.c
updated dgemv_n sgemv_n kernels
=>  updated dgemv_n sgemv_n kernels

benchmark/trsm.c, interface/trsm.c
Use only 1 thread in trsm if m or n < 2*GEMM_MULTITHREAD_THRESHOLD
=>  Use only 1 thread in trsm if m or n < 2*GEMM_MULTITHREAD_THRESHOLD

kernel/x86_64/KERNEL.BULLDOZER, kernel/x86_64/KERNEL.HASWELL, kernel/x86_64/KERNEL.PILEDRIVER, kernel/x86_64/KERNEL.SANDYBRIDGE, kernel/x86_64/dscal.c, kernel/x86_64/dscal_microk_bulldozer-2.c, kernel/x86_64/dscal_microk_haswell-2.c, kernel/x86_64/dscal_microk_sandy-2.c
=> added optimized dscal kernel

kernel/x86_64/KERNEL.BULLDOZER, kernel/x86_64/KERNEL.HASWELL, kernel/x86_64/cscal.c, kernel/x86_64/cscal_microk_haswell-2.c, kernel/x86_64/zscal.c, kernel/x86_64/zscal_microk_bulldozer-2.c, kernel/x86_64/zscal_microk_haswell-2.c
added optimized cscal and zscal functions
=> added optimized cscal and zscal functions

kernel/x86_64/KERNEL.BULLDOZER, kernel/x86_64/KERNEL.PILEDRIVER, kernel/x86_64/KERNEL.SANDYBRIDGE, kernel/x86_64/KERNEL.STEAMROLLER, kernel/x86_64/cscal.c, kernel/x86_64/cscal_microk_bulldozer-2.c, kernel/x86_64/cscal_microk_steamroller-2.c, kernel/x86_64/zscal.c, kernel/x86_64/zscal_microk_steamroller-2.c
added optimized cscal and zscal functions for steamroller
=> added optimized cscal and zscal functions for steamroller

common_arm.h
Bugfix for armv6 memory barrier
=> Bugfix for armv6 memory barrier

benchmark/Makefile, benchmark/copy.c, benchmark/plot-filter.sh
added blas level1 copy benchmark
=> added blas level1 copy benchmark

benchmark/Makefile, benchmark/swap.c
added blas level1 swap  benchmark
=> added blas level1 swap  benchmark

common_arm.h, common_arm64.h
=> bugfix for arm locking

benchmark/Make_exe.sh, benchmark/Makefile, benchmark/cholesky.c, benchmark/potrf.c
bugfixes, to build benchmarks with mingw on Windows OS
=> bugfixes, to build benchmarks with mingw on Windows OS

benchmark/Makefile
bugfix for benchmark Makefile on MAC
=> bugfix for benchmark Makefile on MAC

benchmark/Makefile, benchmark/gesv.c
=> added gesv benchmark

benchmark/gemm.c
=> small modification of gemm.c

benchmark/geev.c, benchmark/scripts/NUMPY/cgemm.py, benchmark/scripts/NUMPY/cgemv.py, benchmark/scripts/NUMPY/daxpy.py, benchmark/scripts/NUMPY/ddot.py, benchmark/scripts/NUMPY/deig.py, benchmark/scripts/NUMPY/dgemm.py, benchmark/scripts/NUMPY/dgemv.py, benchmark/scripts/NUMPY/dgesv.py, benchmark/scripts/NUMPY/dsolve.py, benchmark/scripts/NUMPY/sdot.py, benchmark/scripts/NUMPY/sgemm.py, benchmark/scripts/NUMPY/sgemv.py, benchmark/scripts/NUMPY/zgemm.py, benchmark/scripts/NUMPY/zgemv.py, benchmark/scripts/OCTAVE/cgemm.m, benchmark/scripts/OCTAVE/cgemv.m, benchmark/scripts/OCTAVE/deig.m, benchmark/scripts/OCTAVE/dgemm.m, benchmark/scripts/OCTAVE/dgemv.m, benchmark/scripts/OCTAVE/dsolve.m, benchmark/scripts/OCTAVE/sgemm.m, benchmark/scripts/OCTAVE/sgemv.m, benchmark/scripts/OCTAVE/zgemm.m, benchmark/scripts/OCTAVE/zgemv.m, benchmark/scripts/R/deig.R, benchmark/scripts/R/dgemm.R, benchmark/scripts/R/dsolve.R
=> added benchmark scripts

common_arm64.h
a friend gave me access to arm64 machine.
test: http://notaz.gp2x.de/misc/unsorted/blas_lock_test.c
=> really fix ARM64 locking

lapack-netlib/lapacke/src/lapacke_clantr.c, lapack-netlib/lapacke/src/lapacke_clantr_work.c, lapack-netlib/lapacke/src/lapacke_dlantr.c, lapack-netlib/lapacke/src/lapacke_dlantr_work.c, lapack-netlib/lapacke/src/lapacke_slantr.c, lapack-netlib/lapacke/src/lapacke_slantr_work.c, lapack-netlib/lapacke/src/lapacke_zlantr.c, lapack-netlib/lapacke/src/lapacke_zlantr_work.c
No tests, but happy to add if you can direct me to the harness.
Fixes #631.
@xianyi Please take a look.
=> Fix lantr preparation for row major matrices

lapack-netlib/LAPACKE/src/lapacke_dormlq_work.c
=> Fix Dormlq to perform the correct size operations with RowMajor

lapack-netlib/LAPACKE/src/lapacke_dormbr_work.c
=> Fix Dormbr to perform the correct size operations with RowMajor

common.h, common_stackalloc.h, interface/gemv.c, interface/ger.c
=> Factorize MAX_STACK_ALLOC code to common_stackalloc.h

common_stackalloc.h
* Fix commit 87a2ccc
* Close #736
=> stack alloc: Fix stack smashing detection in 32bits

kernel/arm/KERNEL.ARMV6, kernel/arm/KERNEL.ARMV7, kernel/arm/cdot_vfp.S, kernel/arm/cgemm_kernel_2x2_vfp.S, kernel/arm/cgemm_kernel_2x2_vfpv3.S, kernel/arm/cgemv_n_vfp.S, kernel/arm/cgemv_t_vfp.S, kernel/arm/ctrmm_kernel_2x2_vfp.S, kernel/arm/ctrmm_kernel_2x2_vfpv3.S, kernel/arm/dgemm_kernel_4x2_vfp.S, kernel/arm/dtrmm_kernel_4x2_vfp.S, kernel/arm/dtrmm_kernel_4x4_vfpv3.S, kernel/arm/gemv_n_vfp.S, kernel/arm/gemv_n_vfpv3.S, kernel/arm/gemv_t_vfp.S, kernel/arm/nrm2_vfpv3.S, kernel/arm/sgemm_kernel_4x2_vfp.S, kernel/arm/sgemm_kernel_4x4_vfpv3.S, kernel/arm/strmm_kernel_4x2_vfp.S, kernel/arm/strmm_kernel_4x4_vfpv3.S, kernel/arm/zdot_vfp.S, kernel/arm/zgemm_kernel_2x2_vfp.S, kernel/arm/zgemm_kernel_2x2_vfpv3.S, kernel/arm/zgemv_n_vfp.S, kernel/arm/zgemv_t_vfp.S, kernel/arm/ztrmm_kernel_2x2_vfp.S, kernel/arm/ztrmm_kernel_2x2_vfpv3.S, lapack-netlib/TESTING/nep.in
Ref #740: all assembly codes now clear floating point register correctly
=> Ref #740: all assembly codes now clear floating point register correctly

USAGE.md
Hi,
I think it would help a bit to include some basic usage notes with the sources. Especially on Linux/BSDs it can be easily packaged, shipped with the library and thus provide at least the first hint where to look for help (if nothing else). I have copied some pieces from the github wiki and since I suppose these won't be changing any time soon, the problem of keeping information in two places should not be too bad.
Thank you
Kind Regards
Petr
=> collected usage notes

driver/level2/ztrmv_L.c
Fix #786
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/xianyi/openblas/790)
=> ztrmv_L.c: no longer need a 4kB buffer

common.h, kernel/x86_64/KERNEL.PILEDRIVER, kernel/x86_64/KERNEL.STEAMROLLER, kernel/x86_64/zgemv_n_4.c, kernel/x86_64/zgemv_n_microk_bulldozer-4.c
added optimized zgemv_n kernel for bulldozer, piledriver and steamroller
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/xianyi/openblas/798)
=> Optimized zgemv_n kernel for bulldozer, piledriver and steamroller

benchmark/Makefile
Also revert 0bbca5e
I was not able to reproduce the issue that 0bbca5e was solving, so this commit is only a guess.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/xianyi/openblas/800)
=> Fix smallscaling compilation

kernel/power/KERNEL.POWER8, kernel/power/ddot.c, kernel/power/ddot_microk_power8.c
added optimized ddot kernel for POWER8
=> Ref #795: added optimized ddot kernel for POWER8

kernel/power/KERNEL.POWER8, kernel/power/zdot.c, kernel/power/zdot_microk_power8.c
added optimized zdot kernel for POWER8
=> added optimized zdot kernel for POWER8

kernel/power/KERNEL.POWER8, kernel/power/sdot.c, kernel/power/sdot_microk_power8.c
added optimized sdot kernel for POWER8
=> added optimized sdot kernel for POWER8

kernel/power/KERNEL.POWER8, kernel/power/daxpy.c, kernel/power/daxpy_microk_power8.c
added optimized daxpy kernel for POWER8
=> added optimized daxpy kernel for POWER8

kernel/power/KERNEL.POWER8, kernel/power/zaxpy.c, kernel/power/zaxpy_microk_power8.c
added optimized zaxpy kernel for POWER8
=> added optimized zaxpy kernel for POWER8

kernel/power/KERNEL.POWER8, kernel/power/dscal.c, kernel/power/dscal_microk_power8.c
added optimized dscal kernel for POWER8
=> added optimized dscal kernel for POWER8

kernel/power/KERNEL.POWER8, kernel/power/ccopy.c, kernel/power/ccopy_microk_power8.c, kernel/power/dcopy.c, kernel/power/dcopy_microk_power8.c, kernel/power/dswap.c, kernel/power/dswap_microk_power8.c, kernel/power/scopy.c, kernel/power/scopy_microk_power8.c, kernel/power/sswap.c, kernel/power/sswap_microk_power8.c, kernel/power/zcopy.c, kernel/power/zcopy_microk_power8.c
added optimized copy and swap kernels for POWER8
=> added optimized copy and swap kernels for POWER8

benchmark/Makefile, benchmark/rot.c, kernel/power/KERNEL.POWER8, kernel/power/drot.c, kernel/power/drot_microk_power8.c, kernel/power/srot.c, kernel/power/srot_microk_power8.c
added optimized drot-kernel and srot-kernel for POWER8
=> added optimized drot-kernel and srot-kernel for POWER8

kernel/power/KERNEL.POWER8, kernel/power/cswap.c, kernel/power/cswap_microk_power8.c, kernel/power/sscal.c, kernel/power/sscal_microk_power8.c, kernel/power/zscal.c, kernel/power/zscal_microk_power8.c, kernel/power/zswap.c, kernel/power/zswap_microk_power8.c
added optimized cswap and zswap kernel for POWER8
=> added optimized cswap and zswap kernel for POWER8

kernel/power/KERNEL.POWER8, kernel/power/casum.c, kernel/power/casum_microk_power8.c, kernel/power/dasum.c, kernel/power/dasum_microk_power8.c, kernel/power/sasum.c, kernel/power/sasum_microk_power8.c, kernel/power/zasum.c, kernel/power/zasum_microk_power8.c
added optimized asum kernels for POWER8
=> added optimized asum kernels for POWER8

kernel/power/KERNEL.POWER8, kernel/power/dgemv_n.c, kernel/power/dgemv_n_microk_power8.c
added optimized dgemv_n kernel for POWER8
=> added optimized dgemv_n kernel for POWER8

Makefile.power, Makefile.rule, benchmark/Makefile, benchmark/smallscaling.c, common_power.h, kernel/power/KERNEL.POWER8, kernel/power/dgemm_tcopy_16_power8.S, kernel/power/dgemm_tcopy_logic_16_power8.S, kernel/power/dgemm_tcopy_macros_16_power8.S, kernel/power/sgemm_kernel_16x8_power8.S, kernel/power/sgemm_logic_16x8_power8.S, kernel/power/sgemm_macros_16x8_power8.S, kernel/power/sgemm_tcopy_16_power8.S, kernel/power/sgemm_tcopy_macros_16_power8.S
Optimized sgemm and dgemm for POWER8 and added some small bugfixes
=> Optimized sgemm and dgemm for POWER8

Makefile, ctest/Makefile, test/Makefile, utest/Makefile
Hello! Tests can be compiled just fine when doing cross-compilation.
=> allow building tests when CROSS compiling but don't run them

CONTRIBUTORS.md, kernel/mips/KERNEL.P5600, kernel/mips/dtrsm_kernel_LN_8x4_msa.c, kernel/mips/dtrsm_kernel_LT_8x4_msa.c, kernel/mips/dtrsm_kernel_RN_8x4_msa.c, kernel/mips/dtrsm_kernel_RT_8x4_msa.c
DTRSM optimization for MIPS P5600 and I6400 using MSA
=> DTRSM optimization for MIPS P5600 and I6400 using MSA

interface/swap.c
=> Disable multi-threading in swap

kernel/mips/dtrsm_kernel_LN_8x4_msa.c, kernel/mips/dtrsm_kernel_LT_8x4_msa.c, kernel/mips/dtrsm_kernel_RN_8x4_msa.c, kernel/mips/dtrsm_kernel_RT_8x4_msa.c, kernel/mips/macros_msa.h
=> DTRSM bug fix for MIPS P5600 and I6400

Makefile.system
Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
=> Makefile.system: P5600 and I6400 cores need -mmsa

CONTRIBUTORS.md, kernel/mips/KERNEL.P5600, kernel/mips/dtrsm_kernel_LN_8x4_msa.c, kernel/mips/dtrsm_kernel_LT_8x4_msa.c, kernel/mips/dtrsm_kernel_RN_8x4_msa.c, kernel/mips/dtrsm_kernel_RT_8x4_msa.c, kernel/mips/macros_msa.h, kernel/mips/strsm_kernel_LN_8x8_msa.c, kernel/mips/strsm_kernel_LT_8x8_msa.c, kernel/mips/strsm_kernel_RN_8x8_msa.c, kernel/mips/strsm_kernel_RT_8x8_msa.c
STRSM optimization for MIPS P5600 and I6400 using MSA
Bug fix in dtrsm to use offset argument
=> STRSM optimization for MIPS P5600 and I6400 using MSA

benchmark/Makefile, kernel/power/KERNEL.POWER8, kernel/power/dtrsm_kernel_LT_16x4_power8.S, kernel/power/dtrsm_logic_LT_16x4_power8.S, kernel/power/dtrsm_macros_LT_16x4_power8.S
optimized dtrsm_kernel_LT for POWER8
=> optimized dtrsm_kernel_LT for POWER8

kernel/mips64/axpy.S
=> mips64/axpy: fix error when INCY == 0

interface/lapack/fortran/dlaqr5.f, kernel/power/dtrsm_logic_LT_16x4_power8.S, kernel/power/dtrsm_macros_LT_16x4_power8.S
added experimental support for optimized lapack fortran functions
=> added experimental support for optimized lapack fortran functions

kernel/Makefile.L3, kernel/mips/macros_msa.h, kernel/mips/strsm_kernel_LN_8x8_msa.c, kernel/mips/strsm_kernel_LT_8x8_msa.c, kernel/mips/strsm_kernel_RN_8x8_msa.c, kernel/mips/strsm_kernel_RT_8x8_msa.c
STRSM kernels further optimized for MSA
Removed USE_GEMM3M for mips target
=> STRSM optimized for MSA

Makefile.system, c_check, f_check
Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
=> Complete support for MIPS n32 ABI

lapack-netlib/LAPACKE/src/lapacke_clarfb_work.c, lapack-netlib/LAPACKE/src/lapacke_dlarfb_work.c, lapack-netlib/LAPACKE/src/lapacke_slarfb_work.c, lapack-netlib/LAPACKE/src/lapacke_zlarfb_work.c
=> LAPACKE: fix wrong direction check in LAPACKE_?larfb_work

kernel/mips/dtrsm_kernel_LN_8x4_msa.c, kernel/mips/dtrsm_kernel_LT_8x4_msa.c, kernel/mips/dtrsm_kernel_RN_8x4_msa.c, kernel/mips/dtrsm_kernel_RT_8x4_msa.c, kernel/mips/macros_msa.h, kernel/mips/strsm_kernel_LN_8x8_msa.c, kernel/mips/strsm_kernel_LT_8x8_msa.c, kernel/mips/strsm_kernel_RN_8x8_msa.c, kernel/mips/strsm_kernel_RT_8x8_msa.c
STRSM, DTRSM functions data prefetch added.
=> STRSM, DTRSM functions data prefetch

kernel/mips/cgemm_kernel_8x4_msa.c, kernel/mips/dgemm_kernel_8x4_msa.c, kernel/mips/sgemm_kernel_8x8_msa.c, kernel/mips/zgemm_kernel_4x4_msa.c
SGEMM, DGEMM, CGEMM, ZGEMM functions data prefetch added.
Support for trmm functionality added for dtrmm.
=> SGEMM, DGEMM, CGEMM, ZGEMM functions data prefetch

kernel/generic/trsm_ltcopy_8.c, kernel/generic/zgemm_tcopy_4.c
clang static analyzer points to them.
=> Remove few lines of dead code.

kernel/mips/casum_msa.c, kernel/mips/cdot_msa.c, kernel/mips/dasum_msa.c, kernel/mips/ddot_msa.c, kernel/mips/sasum_msa.c, kernel/mips/sdot_msa.c, kernel/mips/zasum_msa.c, kernel/mips/zdot_msa.c
Add data prefetch in DOT and ASUM functions
=> Add data prefetch in DOT and ASUM functions

kernel/mips/cgemv_n_msa.c, kernel/mips/cgemv_t_msa.c, kernel/mips/zgemv_n_msa.c, kernel/mips/zgemv_t_msa.c
Added prefetch to CGEMV and ZGEMV.
Signed-off-by: Shivraj Patil <shivraj.patil@imgtec.com>
=> Added prefetch to CGEMV and ZGEMV.

benchmark/scripts/R/deig.R, benchmark/scripts/R/dgemm.R, benchmark/scripts/R/dsolve.R
Eliminate GC inside metered loop
Drill through lintr
Reflow w rstudio
=> Improve R benchmark timing

driver/others/blas_server.c, driver/others/memory.c
Ref. #995, may possibly help solve issues seen in 660,883
=> Fix thread data races detected by helgrind 3.12

kernel/mips/KERNEL.P5600, kernel/mips/caxpy_msa.c, kernel/mips/ccopy_msa.c, kernel/mips/cscal_msa.c, kernel/mips/cswap_msa.c, kernel/mips/daxpy_msa.c, kernel/mips/dcopy_msa.c, kernel/mips/dscal_msa.c, kernel/mips/dswap_msa.c, kernel/mips/macros_msa.h, kernel/mips/saxpy_msa.c, kernel/mips/scopy_msa.c, kernel/mips/sscal_msa.c, kernel/mips/sswap_msa.c, kernel/mips/zaxpy_msa.c, kernel/mips/zcopy_msa.c, kernel/mips/zscal_msa.c, kernel/mips/zswap_msa.c
Add msa optimization for AXPY, COPY, SCALE, SWAP
=> Add msa optimization for AXPY, COPY, SCALE, SWAP

driver/others/parameter.c, lapack/lauum/lauum_L_parallel.c, lapack/lauum/lauum_U_parallel.c
prepared parameter.c and lapack/lauum for UNROLL values, that are not a power of two
=> prepared parameter.c for UNROLL values, that are not a power of two

Makefile.install
=> Fix DESTDIR support for cygwin/msys2 install

kernel/mips/KERNEL.P5600, kernel/mips/crot_msa.c, kernel/mips/drot_msa.c, kernel/mips/srot_msa.c, kernel/mips/zrot_msa.c
Added MSA optimised rot functions.
Signed-off-by: Shivraj Patil <shivraj.patil@imgtec.com>
=> Added MSA optimised rot functions.

lapack-netlib/LAPACKE/src/lapacke_claswp_work.c, lapack-netlib/LAPACKE/src/lapacke_dlaswp_work.c, lapack-netlib/LAPACKE/src/lapacke_slaswp_work.c, lapack-netlib/LAPACKE/src/lapacke_zlaswp_work.c
This is a small subset (https://github.com/Reference-LAPACK/lapack/pull/118/commits/07e1fbd89752bed74d35c48e92287d467646a158) of changes committed recently to the Reference LAPACK (https://github.com/Reference-LAPACK/lapack/pull/118). Since I'm not sure whether there is any policy on when and which changes are merged from upstream to OpenBLAS, I'm submitting only changes that prevent our tests (https://github.com/gonum/lapack/pull/219) to pass.
=> LAPACKE: fix incorrect value of lda_t in lapacke_?laswp_work

cpuid_x86.c, driver/others/dynamic.c
Again, but with fixed indention.
=> Enable EXCAVATOR kernels for A12-9800

Makefile.install, blas.pc.in
Fixes https://github.com/xianyi/OpenBLAS/issues/598
=> Install pkg-config files

CMakeLists.txt
Add CMAKE install target (based on patch provided by PrimarchOfTheSpaceWolves in #957)
This was originally merged as 988 but accidentally reverted by my subsequent PR the following day
=> Restore cmake install target

lapack-netlib/LAPACKE/src/lapacke_dormbr.c, lapack-netlib/LAPACKE/src/lapacke_dormbr_work.c, lapack-netlib/LAPACKE/src/lapacke_sormbr.c, lapack-netlib/LAPACKE/src/lapacke_sormbr_work.c
Changes made upstream in Reference LAPACK in
https://github.com/Reference-LAPACK/lapack/pull/128
=> LAPACKE: fix wrong matrix size in ?ormbr

cmake/c_check.cmake
=> Update c_check.cmake to label ppc64 as power ARCH 

common.h, interface/zdot.c, kernel/x86_64/cdot.c, kernel/x86_64/zdot.c
Based in part on #916; fixes #908
=> Fix compilation with PGI by replacing verbatim _real_, _imag_ extensions

cpuid_x86.c
=> Autodetect AMD A8-6410 as BARCELONA

cpuid_x86.c, driver/others/dynamic.c
=> Add an extra familiy/model combination used by AMD Steamrolller.

interface/Makefile, interface/xerbla.c
=> Add trivial implementation of cblas_xerbla

lapack-netlib/LAPACKE/src/lapacke_ctpmqrt.c, lapack-netlib/LAPACKE/src/lapacke_dtpmqrt.c, lapack-netlib/LAPACKE/src/lapacke_stpmqrt.c, lapack-netlib/LAPACKE/src/lapacke_ztpmqrt.c
Copied from https://github.com/Reference-LAPACK/lapack/pull/144
=> Fix workspace computation in LAPACKE ?tpmqrt

common_x86_64.h
Honestly, I didn't spot it at first sight.
=> build: Flang has the same interface as PGI

cpuid_x86.c
=> Revert "Fix unintentional fall-through cases in get_cacheinfo"

interface/zimatcopy.c
Based on Migmuc's patch from #899
=> Fix complex imatcopy for Trans cases with non-square matrix
